---
title: "My cosegregation report"
output:
  html_document:
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
params:
  input: NA
  values: NA
---

```{r,include=FALSE}
source("colourbar.R")
# source("R/contourplot.R")
```

Generated by <span class="typewriter">shinyseg</span> on ``r format(Sys.time(), "%Y-%m-%d %H:%M %Z")``.

### Pedigree table

```{r,echo=FALSE,results="asis",eval=params$values$pedTotal==0}
cat("No families loaded.")
```

```{r,echo=FALSE,results="asis",eval=params$values$pedTotal>0}
cat("`", params$values$pedTotal, "` families loaded.")
```

```{r,echo=FALSE,results="asis",eval=params$values$pedTotal>0}
rhandsontable(
  params$values[["pedData"]],
  useTypes = TRUE,
  manualColumnResize = FALSE,
  rowHeaders = NULL,
  height = 27 + 23 * nrow(params$values[["pedData"]]),
  colHeaders = params$values[["pedNames"]],
  readOnly = TRUE
) %>%
  hot_validate_numeric(col = 9, min = 1, max = 100, allowInvalid = FALSE) %>%
  hot_col(c("ped", "id", "fid", "mid", "sex"), readOnly = TRUE) %>%
  hot_col(6, type = "autocomplete", strict = FALSE, colWidths = "110px") %>% 
  hot_col(7, colWidths = "75px") %>% 
  hot_col(8, colWidths = "90px", halign = "htCenter") %>%
  hot_table(highlightRow = TRUE, contextMenu = FALSE)
```

### Parameters

```{r,echo=FALSE,results="asis",eval=params$values$phenoTotal==0}
cat("Allele frequency: ``", params$values[["afreq"]], "``.<br>")
cat("No phenotypes specified.")
```

```{r,echo=FALSE,results="asis",eval=params$values$phenoTotal>0}
cat("Allele frequency: ``", params$values[["afreq"]], "``.<br>")
cat("Mode: ``", ifelse(params$values[["mode"]] == "rrisk", "Relative risk", "Liability class"), "``.<br>")
cat("Inheritance: ``", params$values[["inheritance"]], "``.<br>")
```

```{r,echo=FALSE,results="asis",eval=params$values$phenoTotal>0 && params$values$mode=="rrisk"}
rhandsontable(
  params$values[["phenoData"]],
  digits = 14,
  useTypes = TRUE,
  manualColumnResize = FALSE,
  rowHeaders = NULL,
  height = 39 + 23 * nrow(params$values[["phenoData"]]),
  colHeaders = c("sex", "phenotype", params$values[["rriskNames"]], "hazard ratio(s)"),
  readOnly = TRUE
) %>%
  hot_col(1, type = "dropdown", source = c("both", "male", "female"), allowInvalid = FALSE, colWidths = "75px") %>%
  hot_col(2, readOnly = TRUE, colWidths = "110px") %>% 
  hot_col(c(3, 6), format = "0,0000") %>% 
  hot_validate_numeric(c(3, 6), min = 0.0001, max = 0.9999, allowInvalid = FALSE) %>%
  hot_validate_numeric(4, min = 0.0001, max = 1000, allowInvalid = FALSE) %>%
  hot_validate_numeric(5, min = 5, max = 1000, allowInvalid = FALSE) %>%
  hot_col(7, type = "autocomplete", colWidths = "130px") %>%
  hot_table(highlightRow = TRUE, contextMenu = FALSE)
```

```{r,echo=FALSE,results="asis",eval=params$values$phenoTotal>0 && params$values$mode=="lclass"}
rhandsontable(
  params$values[["lclassData"]],
  digits = 14,
  useTypes = TRUE,
  manualColumnResize = FALSE,
  rowHeaders = NULL,
  height = 39 + 23 * nrow(params$values[["lclassData"]]),
  colHeaders = unname(params$values[["lclassNames"]]),
  readOnly = TRUE
) %>%
  hot_table(colWidths = "75px") %>% 
  hot_col(1:params$values[["lclassCols"]], format = "0,0000000") %>%
  # hot_validate_numeric(1:params$values[["lclassCols"]], min = 0, max = 1, allowInvalid = FALSE) %>%
  hot_col("sex", type = "dropdown", source = c("", "both", "male", "female"), allowInvalid = FALSE) %>%
  hot_col(params$values[["lclassCols"]] + 2, colWidths = "110px") %>%
  hot_table(highlightRow = TRUE, contextMenu = FALSE)
```

### FLB

```{r,echo=FALSE,results="asis",eval=is.null(params$values$flb)}
cat("No FLB value calculated.")
```

```{r,echo=FALSE,results="asis",eval=!is.null(params$values$flb)}
cat("Bayes factor: ``", params$values[["flb"]], "``.")
```

```{r,echo=FALSE,fig.height=0.8,fig.width=4,eval=!is.null(params$values$flb)}
BFplot(params$values[["flb"]], params$values[["pedTotal"]])
```
