---
output: html_fragment
---

<!-- bayesBox.html is generated from bayesBox.Rmd. Please edit that file -->

Click on <span style='color:#4e4e4e;'><i class='fa-solid fa-calculator fa-fw'></i>Calculate</span> to compute the full-likelihood Bayes factor (FLB) for your analysis, as described by ([Thompson et al., 2003](https://doi.org/10.1086/378100)). You can also use the key below for translating the cosegregation evidence into the ACMG-AMP framework using [Jarvik and Browning's (2016)](https://doi.org/10.1016%2Fj.ajhg.2016.04.003)
thresholds.

Afterward, you may click on <span style='color:#4e4e4e;'><i class='fa-solid fa-rocket fa-fw'></i>Sensitivity</span> to perform sensitivity analyses. Select two analysis parameters from the dropdowns and specify a range of values, then click on <span style='color:#4e4e4e;'><i class='fa-solid fa-chart-area fa-fw'></i>Plot</span>. A contour plot will appear displaying the FLB as a function of the selected parameters, using the same colors from the key from before. If your current parameter values are within the specified ranges, then you will see it as a cross in the graph.

> <i class='fa fa-triangle-exclamation fa-fw' style='color:#db1f48'></i> Calculations may sometimes fail. The main reasons can be numerical problems in the computation of the survival penetrances, Mendelian errors in the pedigree, or other inconsistencies between penetrance and pedigree (e.g., two unaffected parents cannot have an affected child under a full penetrance model). If you cannot figure out the cause, please get in touch!

